# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"getdata": "00_getdata.ipynb"}

modules = ["getdata.py"]

doc_url = "https://fastai.github.io/anti2020ncov/"

git_url = "https://github.com/fastai/anti2020ncov/tree/master/"

def custom_doc_links(name): return None
