# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"#url": "00_digdata.ipynb",
         "url": "01_getdata.ipynb",
         "headers": "01_getdata.ipynb",
         "session": "00_digdata.ipynb",
         "r": "00_digdata.ipynb",
         "#soup": "00_digdata.ipynb",
         "overall_information": "00_digdata.ipynb",
         "province_information": "00_digdata.ipynb",
         "area_information": "00_digdata.ipynb",
         "news_information": "00_digdata.ipynb",
         "dateof": "01_getdata.ipynb",
         "getweb": "01_getdata.ipynb",
         "saveprovice": "01_getdata.ipynb",
         "savecity": "01_getdata.ipynb"}

modules = ["digdata.py",
           "getdata.py"]

doc_url = "https://fastai.github.io/anti2020ncov/"

git_url = "https://github.com/fastai/anti2020ncov/tree/master/"

def custom_doc_links(name): return None
